function cellInfo = mavlink_hil_actuator_controls_t(varargin) 
% MAVLINK_HIL_ACTUATOR_CONTROLS_T returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'mavlink_hil_actuator_controls_t', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'time_usec', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('[us] Timestamp (UNIX Epoch time or time since system boot). The receiving end can infer timestamp format (since 1.1.1970 or since system boot) by checking for the magnitude of the number.')}; ...
{'flags', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Flags as bitfield, 1: indicate simulation using lockstep.')}; ...
{'controls', 16, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('Control outputs -1 .. 1. Channel assignment depends on the simulated hardware.')}; ...
{'mode', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', sprintf('System mode. Includes arming state.')}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
