model_version = 'v1.0.0';
model_name = 'MC Controller';

%% load configuration
load('control_default_config.mat');

%% Constant Variable
CONTROL_CONST.dt = 0.002;   % model execution period

%% Exported Value
CONTROL_EXPORT_VALUE.period = uint32(CONTROL_CONST.dt*1e3);
CONTROL_EXPORT_VALUE.model_info = int8([model_name, ' ', model_version, 0]); % 0 for end of string
% Export to firmware
CONTROL_EXPORT = Simulink.Parameter(CONTROL_EXPORT_VALUE);
CONTROL_EXPORT.CoderInfo.StorageClass = 'ExportedGlobal';

% Airframe id
AIRFRAME = 1;

%% Paramaters
CONTROL_PARAM_VALUE.MC_VEL_XY_P = single(1.4);
CONTROL_PARAM_VALUE.MC_VEL_XY_I = single(0.2);
CONTROL_PARAM_VALUE.MC_VEL_XY_D = single(0.05);
CONTROL_PARAM_VALUE.MC_VEL_Z_P = single(0.5);
CONTROL_PARAM_VALUE.MC_VEL_Z_I = single(0.12);
CONTROL_PARAM_VALUE.MC_VEL_Z_D = single(0);
CONTROL_PARAM_VALUE.MC_VEL_XY_I_MIN = single(-1);
CONTROL_PARAM_VALUE.MC_VEL_XY_I_MAX = single(1);
CONTROL_PARAM_VALUE.MC_VEL_XY_D_MIN = single(-1);
CONTROL_PARAM_VALUE.MC_VEL_XY_D_MAX = single(1);
CONTROL_PARAM_VALUE.MC_VEL_Z_I_MIN = single(-0.2);
CONTROL_PARAM_VALUE.MC_VEL_Z_I_MAX = single(0.2);
CONTROL_PARAM_VALUE.MC_VEL_Z_D_MIN = single(-0.1);
CONTROL_PARAM_VALUE.MC_VEL_Z_D_MAX = single(0.1);
CONTROL_PARAM_VALUE.MC_ROLL_P = single(7);  %%
CONTROL_PARAM_VALUE.MC_PITCH_P = single(7); %%
CONTROL_PARAM_VALUE.MC_ROLL_PITCH_LIM = single(pi/6); %%

CONTROL_PARAM_VALUE.MC_ROLLRATE_P = single(0.15);
CONTROL_PARAM_VALUE.MC_PITCHRATE_P = single(0.15);
CONTROL_PARAM_VALUE.MC_YAWRATE_P = single(0.3);
CONTROL_PARAM_VALUE.MC_ROLLRATE_I = single(0.15);
CONTROL_PARAM_VALUE.MC_PITCHRATE_I = single(0.15);
CONTROL_PARAM_VALUE.MC_YAWRATE_I = single(0.3);
CONTROL_PARAM_VALUE.MC_ROLLRATE_D = single(0.005);
CONTROL_PARAM_VALUE.MC_PITCHRATE_D = single(0.005);
CONTROL_PARAM_VALUE.MC_YAWRATE_D = single(0.002);
CONTROL_PARAM_VALUE.MC_ROLLRATE_FF = single(0.03);
CONTROL_PARAM_VALUE.MC_PITCHRATE_FF = single(0.03);
CONTROL_PARAM_VALUE.MC_YAWRATE_FF = single(0.05);
CONTROL_PARAM_VALUE.MC_RATE_I_MIN = single(-0.2);
CONTROL_PARAM_VALUE.MC_RATE_I_MAX = single(0.2);
CONTROL_PARAM_VALUE.MC_RATE_D_MIN = single(-0.2);
CONTROL_PARAM_VALUE.MC_RATE_D_MAX = single(0.2);
CONTROL_PARAM_VALUE.MC_RATE_XY_LIM = single(pi/2);
CONTROL_PARAM_VALUE.MC_RATE_Z_LIM = single(pi);
CONTROL_PARAM_VALUE.MC_HOVER_THRO = single(0.5);
% Export to firmware
CONTROL_PARAM = Simulink.Parameter(CONTROL_PARAM_VALUE);
CONTROL_PARAM.CoderInfo.StorageClass = 'ExportedGlobal';